WebUbezpieczenia/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUbezpieczenia.BusinessLogic.Managers;
using WebUbezpieczenia.BusinessLogic.Objects;
using WebUbezpieczenia.Managers;
using WebUbezpieczenia.Models;

namespace WebUbezpieczenia.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult Index()
        {
            Models.CustomerViewSearchModel model = new Models.CustomerViewSearchModel();
            //model.lista = new List<ListVi>();
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(Models.CustomerViewSearchModel model)
        {
            CustomerManager m = new CustomerManager();
            DataSet customer = m.LoadCustomersList();
            model.lista = new List<SelectListItem>();
            foreach (DataRow item in customer.Tables[0].Rows)
            {
                
                model.lista.Add(new SelectListItem() { Text = (String)item["NAME"], Value = item["ID"].ToString() });
            }
            return View(model);
        }
        // GET: Customer/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Customer/Create
        public ActionResult Create()
        {
            Models.CustomerViewModels m = new Models.CustomerViewModels();
            //List<SelectListItem> l = new List<SelectListItem>();
            //l.Add(new SelectListItem() { Text = "asdfasd", Value = "asdfs" });
            //l.Add(new SelectListItem() { Text = "xxxx", Value = "fffff" });
            //m.ddTypeList = l;
            using (var con = ConnectionManager.GetConnection())
            {
                CustomerManager mgr = new CustomerManager();
                List<SelectListItem> l = new List<SelectListItem>();
                mgr.LoadUserType(con, l);
                m.ddTypeList = l;
            }
            
            //m.ddTypeList 
            return View(m);
        }

        // POST: Customer/Create
        [HttpPost]
        public ActionResult Create(Models.CustomerViewModels m)
        {
            try
            {               
                ObjectUser o;                
                switch (m.checkBox1)
                {
                    case true:
                        o = new ObjectUser(true);
                        o.RoleID = TUserRole.CustomerWithAccount;
                        o.LoginName = m.LoginName;
                        o.Email = m.Email;
                        o.Pass = m.Password;
                        o.PassConf = m.ConfirmPassword;
                        break;
                    default:
                        o = new ObjectUser(false);
                        o.RoleID = TUserRole.Customer;
                        //set random settings
                        o.LoginName = string.Format("Ra$!d_{0}%", Guid.NewGuid().ToString());
                        o.Email = string.Format("rand_{0}@noemail.com", Guid.NewGuid().ToString());
                        o.Pass = string.Format("%$2a_{0}A{1}", Guid.NewGuid().ToString(), Guid.NewGuid().ToString());
                        o.PassConf = o.Pass;

                        break;
                }
                o.Name = m.Name;
                o.Phone = m.Phone;

                o.CustomerCity = m.CustomerCity;
                o.CustomerPostCode = m.CustomerPostCode;
                o.CustomerStreet = m.CustomerStreet;

                if (o.CustomerData == null)
                    o.CustomerData = new ObjectUserData();

                o.CustomerData.DrivingLicenceStartDate = m.DrivingLicenceStartDate;
                o.CustomerData.Kids = m.Kids;
                o.CustomerData.MaritialStatus = m.MaritialStatus;
                o.CustomerData.Occupation = m.Occupation;
                o.CustomerTypeID = short.Parse(m.ddType);

                string message;
                UserManager mgr = new UserManager(o);
                if (!mgr.Create(out message))
                {
                    ModelState.AddModelError("", message);
                    using (var con = ConnectionManager.GetConnection())
                    {
                        CustomerManager mgrl = new CustomerManager();
                        List<SelectListItem> l = new List<SelectListItem>();
                        mgrl.LoadUserType(con, l);
                        m.ddTypeList = l;
                    }

                    return View(m);                
                }
                else
                {
                    if (m.cbAfterSave)
                    {
                        return RedirectToAction("Edit");
                        //customer to cache
                        //CacheManager.Cache.User = o;
                        //DialogResult = DialogResult.Yes;
                    }
                    //else
                    //DialogResult = DialogResult.OK;
                }


                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Customer/Edit/5
        public ActionResult Edit(int id, int PropertyID = 0)
        {
            CustomerViewEditModel model = new CustomerViewEditModel();
            string errmessage;
            ObjectUser customer = new ObjectUser(false);
            customer.ID = id;
            
            model.FCustomer_Load(customer, out errmessage, PropertyID);
            return View(model);
        }

        // POST: Customer/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Customer/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Customer/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebUbezpieczenia/Controllers/PropertyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUbezpieczenia.BusinessLogic.Objects;
using WebUbezpieczenia.Managers;
using WebUbezpieczenia.Models;

namespace WebUbezpieczenia.Controllers
{
    public class PropertyController : Controller
    {
        // GET: Property
        public ActionResult Index()
        {
            return View();
        }

        // GET: Property/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Property/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Property/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Property/Edit/5
        public ActionResult Edit(int id)
        {
            PropertyViewModels model = new PropertyViewModels();
            ObjectProperty o;
            using (var con = ConnectionManager.GetConnection())
            {
                var m = new BusinessLogic.Managers.PropertyManager();

                var dsFuelType = new DataSet();
                var dsParkingPlace = new DataSet();
                m.LoadDictionaryData(con, dsFuelType, dsParkingPlace);

                model.cbFuelTypeList = m.GetListItem(dsFuelType);

                model.cbParkingPlaceList = m.GetListItem(dsParkingPlace);

                if (id > 0)
                {
                    o = new ObjectProperty();
                    o.ID = id;
                    string message;
                    if (!m.LoadProperty(con, o, out message))
                    {
                        //ErrorManager.Error(message);
                        //BlockUI();
                        //return; //stop execution if error
                    }
                    else
                    {
                        model.tbName = o.Name;
                        model.tbBody = o.Car.Body;
                        model.tbCity = o.Building.City;
                        //model.tbCurrentOwner = o.Car.NumberOfOwners.ToString();
                        //tbExtraProtection.Text = o.Car.Protection;
                        int val;
                        if (int.TryParse(o.Car.Fuel, out val))
                            model.cbFuelType = val.ToString();
                        if (int.TryParse(o.Car.ParkingLocation, out val))
                            model.cbParkingPlace = val.ToString();
                        model.tbPostcode = o.Building.PostCode;
                        //model.tbPreviousInsurer = o.Car.PreviousInsurer;
                        model.tbStreet = o.Building.Street;
                        //model.tbTotalCars = o.Car.NumberOfCars.ToString();
                        //model.cbFromAbroad = o.Car.FromAbroad;
                        model.tbRegNumber = o.RegNumber;
                    }
                }
                //model.ddPropertyType = m.LoadPropertyType(con, model.ddPropertyTypeList, o.PropertyTypeID);
                model.ddPropertyTypeList = new List<SelectListItem>();
                
            }

            return View(model);
        }

        // POST: Property/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Property/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Property/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebUbezpieczenia/Views/Customer/Create.cshtml
@model WebUbezpieczenia.Models.CustomerViewModels

@{
    ViewBag.Title = "Tworzenie klienta";
}

<h2>@ViewBag.Title.</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CustomerViewModels</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.ddType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ddType, new SelectList(Model.ddTypeList, "Value", "Text"))
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.checkBox1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.checkBox1)
                    @Html.ValidationMessageFor(model => model.checkBox1, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>                        

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerStreet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerStreet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerStreet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerPostCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerPostCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerPostCode, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerCity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerCity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerCity, "", new { @class = "text-danger" })
            </div>
        </div>


        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.DrivingLicenceStartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DrivingLicenceStartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DrivingLicenceStartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Occupation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Occupation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Occupation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaritialStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaritialStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaritialStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kids, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kids, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kids, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.LoginName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LoginName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LoginName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cbAfterSave, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.cbAfterSave)
                    @Html.ValidationMessageFor(model => model.cbAfterSave, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebUbezpieczenia/Views/Customer/Details.cshtml
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

WebUbezpieczenia/Views/Customer/Edit.cshtml
@model WebUbezpieczenia.Models.CustomerViewEditModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>CustomerViewModels</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.ddType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ddType, new SelectList(Model.ddTypeList, "Value", "Text"))
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerCity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerCity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerCity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerCity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerStreet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerStreet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerPostCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerPostCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerPostCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DrivingLicenceStartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DrivingLicenceStartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DrivingLicenceStartDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Occupation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Occupation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Occupation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaritialStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaritialStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaritialStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kids, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kids, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kids, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />

        @{ 
            var gridProperty = new WebGrid(Model.propertyList, defaultSort: "Name");
        }
        @gridProperty.GetHtml(
        columns: gridProperty.Columns(

        gridProperty.Column("Nazwa"),
        gridProperty.Column("Rejestracja"),
        gridProperty.Column("Rodzaj"),
        gridProperty.Column(header: "Actions", format: (item) =>
        new HtmlString(
        Html.ActionLink("Wybierz", "Edit", new { id = Model.ID, PropertyID = item.PropertyID }).ToString()
        +
        Html.ActionLink("Edycja", "Edit", "Property", new { id = item.PropertyID }, null).ToString()
        )
        )
        )

        );

        <hr />

        @{
            var grid = new WebGrid(Model.policyList, defaultSort: "Name");
        }
        
        @grid.GetHtml()
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
            }
@{
   // var grid = new WebGrid(Model.propertyList);
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebUbezpieczenia/Views/Customer/Index.cshtml
@model WebUbezpieczenia.Models.CustomerViewSearchModel
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <ul>
            @foreach (var item in Model.lista)
            {
                <li> @Html.ActionLink(item.Text,"Edit", new { Id = item.Value })  </li>
            }
        </ul>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Szukaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}